### ISSUE TITLE
can't read folia xml doc

### ISSUE THREAD

**Issue by Midi77** [proycon/foliapy#17]
When trying to read in this Folia xml doc I get the error: "Exception: FoLiA Document has no version!"
I'm using python 3.7.

**Comment by proycon** [comment]
Hmm, some very old FoLIA documents might perhaps not explicitly indicate their version, perhaps the library needs to make a guess then instead of giving an error. If you can edit the input document, then the quickest way to circumvent this for now is probably to add a version attribute to your FoLiA (root) element, and give it an old value of for example "0.8":

```
<FoLiA version="0.8">

**Comment by proycon** [comment]
This issue should be solved now in foliapy 2.2.5 which I just released
